#!/usr/bin/env bash

set -euo pipefail

cleanup() {
    if [ "$VNC_PASSWORD" ]; then
        /etc/init.d/vnc stop
    fi
    /etc/init.d/xvfb stop
}

trap cleanup EXIT

# Start Xvfb
/etc/init.d/xvfb start
sleep 1

# Start VNC if password exists
if [ "$VNC_PASSWORD" ]; then
    mkdir -p "/.vnc"
    x11vnc -storepasswd "${VNC_PASSWORD}" "/.vnc/passwd"
    /etc/init.d/vnc start
fi

# Run the command
"$@"
exit_value=$?

exit $exit_value

